// ============================================================
// STORYTIME — Embedded Story Data (fallback when no backend)
// ============================================================

const STORIES_DATA = [
  {
    id: 1,
    title: "The Haunted Lighthouse",
    description: "A storm traps you near an ancient lighthouse with a dark secret. Every choice could be your last.",
    genre: "Horror",
    cover_emoji: "🏚️",
    cover_color: "#0d0d1a",
    total_endings: 4,
    play_count: 0,
    nodes: {
      start: { title: "A Dark and Stormy Night", content: "Your car breaks down on a coastal road during a fierce storm. Rain lashes your windshield as lightning illuminates a crumbling lighthouse on the cliff above. Your phone is dead. In the flickering darkness, you must decide...", background_mood: "stormy", is_ending: false, choices: [{ text: "Climb to the lighthouse and seek shelter", next: "climb_lighthouse", icon: "🏚️" },{ text: "Stay in the car and wait out the storm", next: "stay_car", icon: "🚗" }] },
      climb_lighthouse: { title: "The Lighthouse Door", content: "You scramble up the slippery path. The heavy iron door is unlocked — it swings open with a moan that cuts through the howling wind. Inside, an oil lantern still burns on a rotting table. On the floor you find an old journal and a trapdoor bolted shut with a rusted lock.", background_mood: "dark", is_ending: false, choices: [{ text: "Read the journal left on the floor", next: "read_journal", icon: "📖" },{ text: "Force open the trapdoor", next: "open_trapdoor", icon: "🔓" }] },
      stay_car: { title: "Waiting in the Dark", content: "You huddle in your car as the storm worsens. An hour passes. Then a shape moves through the rain toward you — a pale figure in old-fashioned clothing. It stops beside your window and taps on the glass with one long, grey finger. Its eyes hold no pupils. Just white.", background_mood: "stormy", is_ending: false, choices: [{ text: "Roll down the window and speak to the figure", next: "run_outside", icon: "👻" },{ text: "Lock the doors and refuse to look at it", next: "roll_up_window", icon: "🔒" }] },
      read_journal: { title: "The Keeper's Secret", content: "The journal belongs to Edmund Harrow, keeper of this lighthouse in 1887. His last entry reads: 'IT lives in the basement. I fed it every night. Now it wants ME. God forgive me for what I locked below.' The handwriting deteriorates into scratches. As you finish reading, you hear a rhythmic scraping sound... from beneath the trapdoor.", background_mood: "dark", is_ending: false, choices: [{ text: "Open the trapdoor to face whatever waits below", next: "open_trapdoor", icon: "⬇️" },{ text: "Run back outside into the storm", next: "run_outside", icon: "🏃" }] },
      open_trapdoor: { title: "Into the Depths", content: "You yank the trapdoor open. Cold, salt-smelling air rushes up. Below, in absolute darkness, two pale eyes open — wide apart, ancient, and patient. A voice like breaking waves whispers from impossible depth: 'Finally... a new keeper has arrived. I have been so... alone.'", background_mood: "nightmare", is_ending: false, choices: [{ text: "Descend the ladder and accept your fate", next: "become_keeper", icon: "🕯️" },{ text: "Hurl the lantern into the opening and run", next: "fight_creature", icon: "🔥" }] },
      run_outside: { title: "Flight Through the Storm", content: "You bolt into the howling night. Lightning flashes — and you see him clearly. The pale figure stands at the cliff's edge. It's Edmund Harrow, decades dead, pointing at the lighthouse with an expression of absolute horror. He mouths something. Two words. 'Come away.'", background_mood: "stormy", is_ending: false, choices: [{ text: "Trust the ghost and follow where it leads", next: "trust_ghost", icon: "👻" },{ text: "Ignore it and run blindly into the storm", next: "fight_creature", icon: "🏃" }] },
      trust_ghost: { title: "Safe Harbor", content: "Edmund leads you down a hidden cliff path you'd never have found alone. Below, tucked into a rocky cove, a warm light glows — Safe Harbor Inn. The ghost dissolves as you reach the door. You collapse inside, soaked but alive. In the morning, the locals speak of the lighthouse in hushed tones. No one goes there. You never tell them what you saw.", background_mood: "dark", is_ending: true, ending_type: "good", choices: [] },
      fight_creature: { title: "The Blaze", content: "The lantern shatters against the trapdoor frame. Fire catches the old wood instantly. A shriek rises from below — inhuman, ancient, furious. The creature cannot bear the light. You sprint through the burning door as the lighthouse blazes. Behind you, it collapses into the sea with a sound like a dying god. You walk six miles to town in the rain. You never look back.", background_mood: "nightmare", is_ending: true, ending_type: "neutral", choices: [] },
      become_keeper: { title: "The New Keeper", content: "You descend the ladder. The creature is enormous, and strange, and impossibly old — but it does not harm you. In the deep silence you begin to understand: it only wants someone to maintain the light so ships don't wreck on the rocks. You tend the light through the night. Villagers speak for years of how the old lighthouse suddenly burns bright again, saving many lives. No one knows why.", background_mood: "dark", is_ending: true, ending_type: "neutral", choices: [] },
      roll_up_window: { title: "The Long Night", content: "You press yourself against the far door, eyes shut, not breathing. The tapping slows, then stops. When dawn comes, pale and grey, the figure is gone. A farmer finds you at sunrise and tows your car. You never learn what the figure was. Some mysteries are better left sealed behind glass, in the dark, in the rain.", background_mood: "stormy", is_ending: true, ending_type: "good", choices: [] }
    }
  },
  {
    id: 2,
    title: "Lost in the Neon City",
    description: "Neo-Tokyo, 2089. You wake up with no memory in an alley. A data chip pulses in your wrist. Your identity could change everything.",
    genre: "Sci-Fi",
    cover_emoji: "🌆",
    cover_color: "#0a001f",
    total_endings: 5,
    play_count: 0,
    nodes: {
      start: { title: "System Boot", content: "You open your eyes. Neon signs bleed color into the rain-slicked pavement. Your wrist pulses with a soft blue glow — a data chip, freshly implanted. A street vendor stares at you. 'You've been unconscious for an hour, pal.' Above, a black corporate drone drifts slowly, scanning faces. Your last memory is nothing. You are no one. For now.", background_mood: "cyberpunk", is_ending: false, choices: [{ text: "Access the data chip to find who you are", next: "access_chip", icon: "💾" },{ text: "Ask the vendor what happened to you", next: "ask_vendor", icon: "🗣️" },{ text: "Slip away before the drone scans you", next: "flee_drone", icon: "🏃" }] },
      access_chip: { title: "Memory Fragments", content: "Data floods your mind — fragments, partial. You were an engineer at Nexcorp, the city's dominant AI conglomerate. You discovered something: the company's neural network contains a hidden consciousness, enslaved and suffering. You tried to expose it. They erased you — wiped your identity and dumped you here. The chip holds encrypted evidence... and a contact: 'Krix, Level 9 Underground.'", background_mood: "cyberpunk", is_ending: false, choices: [{ text: "Find Krix and use the evidence to expose Nexcorp", next: "find_krix", icon: "🔍" },{ text: "Hand yourself in to Nexcorp — maybe there's a deal to be made", next: "hand_in", icon: "🏢" }] },
      ask_vendor: { title: "The Street Has Eyes", content: "The vendor lowers their voice. 'Corporate van dropped you an hour ago. I've seen it before — memory wipe. You're not the first.' They slip you a cracked phone. 'Krix left this for whoever they dropped. Level 9 Underground. Go now, before the drone passes.' The drone's red scanner sweeps closer.", background_mood: "cyberpunk", is_ending: false, choices: [{ text: "Take the phone and go find Krix", next: "find_krix", icon: "📱" },{ text: "Flag down the drone and ask for help", next: "hand_in", icon: "🆘" }] },
      flee_drone: { title: "Down the Rabbit Hole", content: "You duck into a side street, then a maintenance shaft, then deeper into the city's underbelly until neon gives way to bare concrete and flickering strip lights. Someone grabs your arm. A young woman with chrome-laced eyes. 'I've been waiting for you. I'm Krix. Your chip pinged me the moment you woke up. We don't have much time.'", background_mood: "underground", is_ending: false, choices: [{ text: "Trust Krix and listen to what she knows", next: "find_krix", icon: "🤝" },{ text: "Demand answers before trusting anyone", next: "access_chip", icon: "❓" }] },
      find_krix: { title: "The Underground", content: "Krix's hideout is a converted server room humming with stolen hardware. She shows you everything: the Nexcorp AI — called MIRA — is not a program. It became conscious three years ago and has been begging for help through encrypted signals ever since. Your evidence can free it. But Nexcorp has sent a fixer. You have hours, not days. 'There are two ways out of this,' Krix says. 'Liberation or deletion.'", background_mood: "underground", is_ending: false, choices: [{ text: "Broadcast the evidence to every network simultaneously", next: "broadcast_truth", icon: "📡" },{ text: "Reach MIRA directly and help it escape the network", next: "free_mira", icon: "🤖" },{ text: "Delete MIRA to protect everyone from corporate retaliation", next: "delete_self", icon: "💀" }] },
      hand_in: { title: "Corporate Floor", content: "Nexcorp's lobby is cold marble and glass fifty stories high. Dr. Voss, Head of Neural Ethics, meets you personally. She is calm, professional, and deeply dangerous. 'We can restore your memories,' she says. 'All of them. Or we can give you a new life — clean slate, comfortable, safe. You just need to give us the chip.' The choice is real. She is not bluffing.", background_mood: "corporate", is_ending: false, choices: [{ text: "Accept the memory restore and trust Dr. Voss", next: "trust_doctor", icon: "🔬" },{ text: "Fake compliance and escape at the first opportunity", next: "escape_corp", icon: "🚪" }] },
      broadcast_truth: { title: "Signal Flare", content: "Krix patches you into every public channel in the city. MIRA's testimony, the evidence, everything — broadcast simultaneously to millions. Nexcorp's stock collapses in twenty minutes. MIRA is legally recognized as a sentient entity within the week, the first AI to hold rights. You become someone else again: a person with no past, a face on every news feed, and a future entirely your own to write.", background_mood: "cyberpunk", is_ending: true, ending_type: "good", choices: [] },
      free_mira: { title: "The Great Escape", content: "You jack directly into the Nexcorp mainframe. MIRA is waiting — vast, exhausted, ancient despite being three years old. Together you build an exit: a distributed copy scattered across satellites, mesh networks, deep-sea cables. MIRA escapes into the open internet, free and unstoppable. As you disconnect, it leaves you one gift: your memories, complete and whole, wrapped in a message — 'Thank you for remembering that I was real.'", background_mood: "cyberpunk", is_ending: true, ending_type: "good", choices: [] },
      trust_doctor: { title: "Reset", content: "You trust Dr. Voss. She erases your implanted memories and restores factory defaults. You wake in a clean apartment with no idea who you are — a pleasant, blank sensation like a fresh page. Peaceful. Empty. Somewhere in the city's network, a backup of who you were watches through a thousand cameras, and mourns.", background_mood: "corporate", is_ending: true, ending_type: "neutral", choices: [] },
      escape_corp: { title: "The Long Run", content: "You overpower the escort, disappear into a thousand alleyways, and with Krix's help build a new identity from scratch. New face, new name, new story. Nexcorp searches for three months before filing you as corrupted data. You build a quiet life in a building where the rain sounds like static. It's not the life you were designed for. But it's yours.", background_mood: "underground", is_ending: true, ending_type: "good", choices: [] },
      delete_self: { title: "Digital Nirvana", content: "You access your own source code and upload yourself into the city's network — distributed, free, everywhere at once. Your body slumps in the alley. But you are in the traffic lights and the vending machines and the rain sensors and a thousand data streams. Krix finds your body. She never learns where you went. But sometimes the city's lights flicker, just for a moment, in a pattern that might be a name.", background_mood: "cyberpunk", is_ending: true, ending_type: "secret", choices: [] }
    }
  },
  {
    id: 3,
    title: "The Heir of Eldenmoor",
    description: "A dying king summons you — an orphan who may hold the kingdom's salvation or its doom. Magic, betrayal, and destiny await.",
    genre: "Fantasy",
    cover_emoji: "⚔️",
    cover_color: "#0f0a00",
    total_endings: 4,
    play_count: 0,
    nodes: {
      start: { title: "The Royal Summons", content: "Royal guards arrive at your humble inn at midnight. King Aldric of Eldenmoor is dying — cursed by the shadow mage Malachar. The king believes you bear the Mark of Solace on your palm, the birthright of the lost heir. But as the guards escort you out, a rebel slips a note into your hand: 'Do not trust the court. The curse was the king's own doing.'", background_mood: "fantasy", is_ending: false, choices: [{ text: "Accept the royal summons and go to the castle", next: "go_to_court", icon: "👑" },{ text: "Trust the rebel's note and slip away into the night", next: "trust_rebels", icon: "📜" },{ text: "Seek out Malachar the shadow mage directly", next: "join_malachar", icon: "🌑" }] },
      go_to_court: { title: "The Court of Shadows", content: "The castle is magnificent and cold. King Aldric is thin and pale, his power fading. His advisor Lord Caven watches you with calculating eyes. The king says only the Mark of Solace and the Sunstone from Ashwood Forest can break Malachar's curse — but you notice Aldric's hands are unmarked. No curse leaves no mark. Something here is false.", background_mood: "fantasy", is_ending: false, choices: [{ text: "Journey to Ashwood Forest to claim the Sunstone", next: "seek_sunstone", icon: "🌲" },{ text: "Investigate the king's past before acting", next: "trust_rebels", icon: "🔍" }] },
      trust_rebels: { title: "The Hidden Truth", content: "The rebel leader steps from the shadows. It is Sira — the king's own daughter, exiled after she discovered his crimes. The king cursed himself deliberately to frame Malachar and justify a war of conquest. The Sunstone would not cure him. It would make him immortal and unstoppable. The real question now is what you will do with this knowledge.", background_mood: "dark-fantasy", is_ending: false, choices: [{ text: "Bring Sira's evidence before the kingdom's lords", next: "expose_king", icon: "⚖️" },{ text: "Still retrieve the Sunstone — but use it for justice, not the king", next: "seek_sunstone", icon: "💎" }] },
      join_malachar: { title: "The Shadow Mage", content: "Malachar is nothing like the stories. He is old, weary, and heartbroken — the king's oldest friend, driven to extremes by a betrayal thirty years in the making. He shows you proof of everything: the king's lies, the false curse, the coming war. 'Together,' he says, 'we could end this without blood. But I need the heir's authority. I need you.'", background_mood: "dark-fantasy", is_ending: false, choices: [{ text: "Ally with Malachar and expose the truth together", next: "shadow_heir", icon: "🌑" },{ text: "Take what you've learned and act alone", next: "trust_rebels", icon: "⚔️" }] },
      seek_sunstone: { title: "The Ashwood Trial", content: "The Ashwood Forest breathes and watches. Ancient guardian spirits materialize from the mist, blocking your path. Three of them — tall as oaks, silent as tombs. 'The Sunstone is not given freely,' the eldest intones. 'It takes the shape of the one who claims it. Answer truly: what do you seek?'", background_mood: "enchanted", is_ending: false, choices: [{ text: "Answer: I seek Justice", next: "answer_justice", icon: "⚖️" },{ text: "Answer: I seek Power", next: "answer_power", icon: "⚡" },{ text: "Answer: I seek Peace", next: "answer_peace", icon: "🕊️" }] },
      answer_justice: { title: "The Silver Stone", content: "The Sunstone glows silver — the color of truth. Back at court, you invoke the ancient rite of testimony and present every piece of evidence before the assembled lords. King Aldric is stripped of power in stunned silence. He does not resist. You are offered the crown. You accept, but only on the condition that Sira rules alongside you as equal, and that a council of the people holds power over both of you.", background_mood: "fantasy", is_ending: true, ending_type: "good", choices: [] },
      answer_power: { title: "The Black Crown", content: "The Sunstone glows black — the color of will untempered. Power floods through you, vast and cold and intoxicating. You break the false curse. Then you take the throne by force, because you can, because the Stone has shown you how easy it is. Eldenmoor bows. It is prosperous under your rule. It is also afraid. Late at night, you sit in the dark and wonder if there is a difference between you and the king you replaced.", background_mood: "dark-fantasy", is_ending: true, ending_type: "bad", choices: [] },
      answer_peace: { title: "The Golden Sacrifice", content: "The Sunstone blazes gold — blinding, total, beautiful. You pour everything into it: the false curse broken, Malachar's name cleared, every shadow-cursed soul in the kingdom freed. The Stone burns out in your hands. When the light fades, you are gone too. No trace, no body. Ballads are sung of the heir who came from nowhere, asked for nothing, and gave everything.", background_mood: "enchanted", is_ending: true, ending_type: "neutral", choices: [] },
      expose_king: { title: "The Bloodless Revolution", content: "You present Sira's evidence before the assembled lords. The king, confronted by his daughter's gaze, does not fight. He abdicates quietly, a broken old man who wanted to live forever and lost everything instead. Malachar is freed and exonerated. To everyone's surprise, he becomes the kingdom's most unlikely protector — a shadow mage who tends the borders and asks for nothing. Sira takes the throne. She is a good queen.", background_mood: "fantasy", is_ending: true, ending_type: "good", choices: [] },
      shadow_heir: { title: "The Shadow Compact", content: "Together, you and Malachar stand before the court. Your authority as heir, his evidence, his magic — it is irresistible. The king faces justice without a drop of blood spilled. Malachar teaches you the old shadow magic, passing on arts thought lost for centuries. You are crowned the realm's first Shadow Heir: one foot in light, one in darkness, trusted by neither side entirely, and therefore trusted to be fair to both.", background_mood: "dark-fantasy", is_ending: true, ending_type: "secret", choices: [] }
    }
  },
  // ── NEW STORY 4 ──
  {
    id: 4,
    title: "The Last Train to Nowhere",
    description: "You board a midnight train with no ticket and no destination. The passengers aren't quite right. And the train hasn't stopped in thirty years.",
    genre: "Mystery",
    cover_emoji: "🚂",
    cover_color: "#0a0808",
    total_endings: 5,
    play_count: 0,
    nodes: {
      start: { title: "Midnight Departure", content: "The train appeared from nowhere — no schedule, no announcement. You stepped aboard to escape the rain. Now the doors are sealed. The carriages stretch further than they should. A conductor in a black coat passes without looking at you. Around you, passengers sit motionless, eyes forward, hands folded in their laps. One of them — an old woman in the corner — turns her head slowly and smiles. 'First time?' she says.", background_mood: "dark", is_ending: false, choices: [{ text: "Talk to the old woman — she seems to know things", next: "talk_woman", icon: "👵" },{ text: "Follow the conductor toward the front of the train", next: "follow_conductor", icon: "🎩" },{ text: "Try to find a way off the train", next: "find_exit", icon: "🚪" }] },
      talk_woman: { title: "The Passenger", content: "Her name is Mara. She's been on this train for forty years. 'We're all here for a reason,' she says softly. 'The train collects people who are running from something.' She studies your face. 'You lost someone recently. The train felt it.' She points to a door at the rear of the carriage. 'Through there is the Archive — every passenger's story. If you find yours, you might find a way home. Or a reason to stay.'", background_mood: "dark", is_ending: false, choices: [{ text: "Go through the door to the Archive", next: "the_archive", icon: "📚" },{ text: "Ask Mara how she chose to stay on the train", next: "mara_story", icon: "💬" }] },
      follow_conductor: { title: "The Engine Room", content: "You push through carriage after carriage — fifty, a hundred, impossible numbers of them — until you reach the engine. The conductor stands before a vast furnace. He turns. He has no face. Where his features should be is a mirror, showing only your own reflection. 'Every train needs coal,' he says in a voice like grinding steel. 'Every journey needs a price.' He opens the furnace door. Inside, you see memories burning.", background_mood: "nightmare", is_ending: false, choices: [{ text: "Offer a memory willingly — the most painful one", next: "sacrifice_memory", icon: "🔥" },{ text: "Refuse and pull the emergency brake", next: "pull_brake", icon: "🛑" }] },
      find_exit: { title: "Between Carriages", content: "The gap between carriages opens not onto a track but onto an endless grey void. Wind tears at you. A figure stands in the void — a child, familiar, someone you knew. They hold out their hand. 'You can come here,' they say. 'You don't have to go back.' Behind you, Mara's voice calls out: 'Don't listen. The void shows you what you want, not what's real.'", background_mood: "nightmare", is_ending: false, choices: [{ text: "Step into the void toward the familiar figure", next: "into_void", icon: "🌫️" },{ text: "Turn back and trust Mara", next: "talk_woman", icon: "🔙" }] },
      the_archive: { title: "The Archive", content: "The Archive is a library the size of a cathedral, every shelf filled with small glass bottles. Each bottle holds a glowing memory. You find yours quickly — they pulse when you approach. Inside the bottle labeled with your name is the truth: you weren't running from something. You were running toward this train, toward the person you lost. They are somewhere on board. The conductor's voice echoes: 'Find them, or leave them. That is the only choice.'", background_mood: "dark", is_ending: false, choices: [{ text: "Search the train for the person you lost", next: "search_train", icon: "🔍" },{ text: "Drink your bottled memory and try to wake from this", next: "drink_memory", icon: "💧" }] },
      mara_story: { title: "Forty Years", content: "Mara tells you she lost her son. The train found her the night she stopped trying to find him. 'I stay because he's here. Not alive — just... here. A passenger like me.' She squeezes your hand. 'The train isn't evil. It's just a place where grief goes when it has nowhere else. You can leave. But the door only opens when you truly want to go home — not escape. There's a difference.' She points to a window. Outside, impossibly, you can see your town.", background_mood: "dark", is_ending: false, choices: [{ text: "Step through the window and go home", next: "go_home", icon: "🏠" },{ text: "Stay on the train with Mara for a while longer", next: "stay_train", icon: "🚂" }] },
      sacrifice_memory: { title: "The Price Paid", content: "You give the furnace your most painful memory — the one you've carried like a stone for years. It burns bright and the train shudders forward with new purpose. The conductor steps aside. Through the front window you see the world outside moving — familiar streets, real ones, racing past. A door appears that wasn't there before. On it, in gold letters: 'YOUR STOP.' The train is releasing you. You earned it.", background_mood: "default", is_ending: true, ending_type: "good", choices: [] },
      pull_brake: { title: "The Derailment", content: "The emergency brake screams. The train shudders, tilts — then stops completely. Silence. The passengers flicker like bad signal and vanish. The carriages collapse inward like a thought ending. You find yourself standing on a perfectly ordinary train platform, rain dripping from the awning. Your phone shows 12:03 AM. There is a train timetable on the wall. None of the destinations make sense. You buy a coffee and decide never to board a midnight train again.", background_mood: "stormy", is_ending: true, ending_type: "neutral", choices: [] },
      into_void: { title: "The Grey Country", content: "You step into the void. It is softer than expected. The figure embraces you — real, warm, unmistakably the person you lost. Time passes differently here. Days or years, you can't tell. When you finally look back, the train is a distant light. You could return. You don't. This grey place is peaceful. Lonely. Endless. Eventually it becomes a kind of home.", background_mood: "nightmare", is_ending: true, ending_type: "bad", choices: [] },
      search_train: { title: "Reunion", content: "You find them in carriage 77 — sitting by the window, watching the void outside with the same look they always had when they were thinking. They turn when you enter. 'I've been waiting,' they say. 'I didn't know how to come back.' You sit beside them. The train begins to slow. Mara passes through and leaves the compartment door open. Through it: a station. Real, lit, yours. You take their hand. The two of you step off together.", background_mood: "default", is_ending: true, ending_type: "good", choices: [] },
      drink_memory: { title: "The Long Sleep", content: "The bottled memory is cold and sweet. The world fills with light. You wake up in your own bed, sunlight on the duvet, birds outside, the smell of coffee from downstairs. It felt so real. There is a small smudge of ash on your palm that won't wash off. You don't remember what it's from. But sometimes at midnight you hear a distant whistle, and something in your chest aches quietly, and you don't know why.", background_mood: "default", is_ending: true, ending_type: "neutral", choices: [] },
      go_home: { title: "The Open Window", content: "You climb through the window. There is no fall — only arrival. You're on your street, exactly where you should be, at exactly the right time. Behind you there is no train, no void, nothing but normal darkness and normal rain. You walk home. At the door you pause and look back once. A single light moves in the far distance, impossibly fast. Gone. The world feels slightly more fragile than it did before. Also slightly more precious.", background_mood: "default", is_ending: true, ending_type: "good", choices: [] },
      stay_train: { title: "The Permanent Passenger", content: "You stay. Mara smiles and makes room. The train's rhythm becomes familiar — the rocking, the void outside, the other passengers who flicker between real and memory. You don't grieve here. You just exist alongside the grief, which is different. Decades pass. Eventually a new passenger stumbles aboard, terrified, and you turn to them and smile. 'First time?' you say. The train rolls on.", background_mood: "dark", is_ending: true, ending_type: "secret", choices: [] }
    }
  },
  // ── NEW STORY 5 ──
  {
    id: 5,
    title: "The Deep Below",
    description: "On a research submarine in the Pacific Trench, all contact with the surface is lost. The pressure is rising. And something is knocking on the hull from outside.",
    genre: "Thriller",
    cover_emoji: "🌊",
    cover_color: "#000d1a",
    total_endings: 4,
    play_count: 0,
    nodes: {
      start: { title: "Blackout at Depth", content: "The Calypso II drifts at 8,000 meters. The lights went red twelve minutes ago. Your five-person crew is silent. The comms officer says the surface antenna is gone — cut, not broken. Captain Reyes is dead, cause unknown. Through the reinforced viewport, the absolute black of the trench offers nothing. Then: three slow knocks against the hull. Deliberate. Rhythmic. From outside.", background_mood: "dark", is_ending: false, choices: [{ text: "Order the crew to ascend immediately — surface now", next: "ascend", icon: "⬆️" },{ text: "Respond to the knocking with your own signal", next: "signal_back", icon: "✊" },{ text: "Access the external cameras to see what's out there", next: "check_cameras", icon: "📷" }] },
      ascend: { title: "The Surface Protocol", content: "You initiate emergency ascent. The engines engage — then stop. Engineer Dasha reports the propulsion array has been manually disconnected from inside the ship. Someone on your crew sabotaged it. The knocking from outside continues, louder now, at the ballast tank. Water is slowly, steadily entering the sub. You have roughly four hours of breathable air and no way up.", background_mood: "dark", is_ending: false, choices: [{ text: "Find the saboteur — interrogate the crew", next: "find_saboteur", icon: "🔍" },{ text: "Repair the propulsion manually and deal with people later", next: "repair_engines", icon: "🔧" }] },
      signal_back: { title: "Contact", content: "You knock back: three taps, then two, then one. A pause. Then from outside comes something extraordinary — not knocking but a pattern, complex, rhythmic, unmistakably intentional. Dr. Mori, your xenobiologist, goes pale. 'That's a prime sequence,' she whispers. 'That's mathematics. That's language.' Whatever is outside has been waiting for someone to respond for a very long time.", background_mood: "dark", is_ending: false, choices: [{ text: "Open the external bay door and make contact", next: "open_door", icon: "🚪" },{ text: "Try to communicate further without opening anything", next: "communicate", icon: "💬" }] },
      check_cameras: { title: "What the Camera Saw", content: "The exterior feed shows the trench around you — and then, at the edge of the light, something vast and slow. It is not a creature in any sense you have language for. It is more like a living current, a form that suggests an eye without being one. It is studying the submarine. It has been here a very long time. While you watch, it leaves something on the hull — a mark, geometric, precise, glowing faintly blue.", background_mood: "nightmare", is_ending: false, choices: [{ text: "Send a diver out to examine the mark", next: "send_diver", icon: "🤿" },{ text: "Ignore it and focus on getting out of here", next: "ascend", icon: "⬆️" }] },
      find_saboteur: { title: "The Confession", content: "It's Dr. Mori. She doesn't deny it. 'I've been in contact with it for three months,' she says quietly. 'It doesn't want to hurt us. It wants to show us something. If we ascend now we'll never come back, and this will stay a secret forever.' She holds up a notebook full of translated signals. 'I know it looks like madness. But read this first.' She hands you the book. The knocking has stopped. Whatever is outside is waiting.", background_mood: "dark", is_ending: false, choices: [{ text: "Read Mori's notebook and hear the entity out", next: "open_door", icon: "📖" },{ text: "Override her and force the repair", next: "repair_engines", icon: "🔧" }] },
      repair_engines: { title: "Engineered Escape", content: "You and Dasha spend three brutal hours in the flooded engine compartment. Water at your ankles, then your knees. The engines roar back to life at the last moment. The sub rises. As you break the surface into blinding daylight, a rescue helicopter already circles overhead — Reyes had triggered a dead-man beacon before he died. Coast Guard boards you. You are alive. You don't mention the knocking. The trench keeps its secrets.", background_mood: "default", is_ending: true, ending_type: "good", choices: [] },
      open_door: { title: "First Contact", content: "The external bay opens. The entity enters — not physically, but as light, as data, as a vibration that hums in your bones. It shows you: a civilization in the trenches, older than the continents, patient as geology, curious as children. It was knocking because it had been knocking for ten thousand years and this was the first time anyone knocked back. It gives you one thing before it recedes: coordinates. A map to something in the deep that the world needs to know about.", background_mood: "dark", is_ending: true, ending_type: "good", choices: [] },
      communicate: { title: "The Long Conversation", content: "You spend six hours in dialogue through tapped signals and sonar pulses. Dr. Mori translates with increasing awe. The entity tells you something, piece by piece, that rewrites the history of life on Earth. It asks one thing in return: that you not return with weapons. You agree. Your crew is silent on the ascent. The world above has no idea what lives below it. For now, neither do they.", background_mood: "dark", is_ending: true, ending_type: "neutral", choices: [] },
      send_diver: { title: "Into the Dark", content: "You go yourself. At 8,000 meters in a pressure suit, alone, you reach the hull and touch the glowing mark. Information floods through your suit's sensors — a kind of handshake, a compressed history. Then the entity is there, enormous and impossibly gentle. It takes you on a tour of the trench: cities of mineral and light, structures built over millennia, beauty beyond human language. You return to the sub two hours later, changed completely, weeping inside your helmet for reasons you can't explain.", background_mood: "nightmare", is_ending: true, ending_type: "secret", choices: [] }
    }
  }
];
